'use strict';

module.exports = function(req, res) {
    console.log(req.body);
    res.json({
        status: 0,
        orders: [{
            order_code:      '0000',
            order_type:      'ORDINARY_ORDER',
            order_state:     'REQUESTING',
            order_remark:    'なにそのチョンマゲ',
            drafting_date:   '2015/08/01',
            drafter_code:    '1853',
            drafter_account: 'm-perry',
            department_code: '0001',
            department_name: '内科',
            trader_code:     '0000',
            trader_name:     '阿漕商店',
            products: [
                {
                    code:     '0000',
                    name:     'タイガーマスク',
                    maker:    '梶原一騎',
                    min_price:    43.00,
                    cur_price:    43.01,
                    max_price:    43.02,
                    quantity: 8,
                    state:    'UNORDERED',
                    billing_amount:      0,
                    last_edited_date:    '2015/08/01',
                    last_editor_code:    '1853',
                    last_editor_account: 'm-perry',
                },
                {
                    code:     '4126',
                    name:     'マングローブ',
                    maker:    '亜熱帯潮間帯',
                    min_price:    11.92,
                    cur_price:    11.92,
                    max_price:    11.92,
                    quantity: 3,
                    state:    'ORDERED',
                    billing_amount:      0,
                    last_edited_date:    '2015/09/11',
                    last_editor_code:    '1192',
                    last_editor_account: 'y-minamoto',
                }
            ],
            last_modified_date:    '2015/10/10',
            last_modifier_code:    '1603',
            last_modifier_account: 'y-tokugawa'
        },
        {
            order_code:      '4219',
            order_type:      'URGENCY_ORDER',
            order_state:     'APPROVING',
            order_remark:    'それで何を表現しようと言うの?',
            drafting_date:   '2015/08/01',
            drafter_code:    '1853',
            drafter_account: 'm-perry',
            department_code: '0002',
            department_name: '中科',
            trader_code:     '0001',
            trader_name:     'バッタモン市場',
            products: [
                {
                    code:     '0001',
                    name:     '危険薬',
                    maker:    '酩酊ラリ子',
                    min_price:    43.01,
                    cur_price:    43.02,
                    max_price:    43.03,
                    quantity: 666,
                    state:    'UNORDERED',
                    billing_amount:      0,
                    last_edited_date:    '2015/09/18',
                    last_editor_code:    '1853',
                    last_editor_account: 'm-perry',
                },
                {
                    code: '   0645',
                    name:     'STAP細胞',
                    maker:    '小保方製薬',
                    min_price:    11.92,
                    cur_price:    11.92,
                    max_price:    11.92,
                    quantity: 9,
                    state:    'ORDERED',
                    billing_amount:      0,
                    last_edited_date:    '2015/09/18',
                    last_editor_code:    '1853',
                    last_editor_account: 'm-perry',
                }
            ],
            last_modified_date: '2015/10/10',
            last_modifier_code: '1603',
            last_modifier_account: 'k-katsu'
        },
        {
            order_code:      '1818',
            order_type:      'ORDINARY_ORDER',
            order_state:     'APPROVED',
            order_remark:    '開国いいよ〜',
            drafting_date:   '2015/03/02',
            drafter_code:    '1853',
            drafter_account: 'm-perry',
            department_code: '0000',
            department_name: '外科',
            trader_code:     '0001',
            trader_name:     'バッタモン市場',
            products: [
                {
                    code:     '0710',
                    name:     'アレ',
                    maker:    '秘密のアッコちゃん',
                    min_price:    893.00,
                    cur_price:    893.01,
                    max_price:    893.02,
                    quantity: 42,
                    state:    'UNORDERED',
                    billing_amount:      0,
                    last_edited_date:    '2015/09/18',
                    last_editor_code:    '1853',
                    last_editor_account: 'm-perry',
                },
                {
                    code: '   0794',
                    name:     'ソレ',
                    maker:    'クレヨンしんちゃん',
                    min_price:    29.29,
                    cur_price:    29.92,
                    max_price:    29.92,
                    quantity: 9,
                    state:    'ORDERED',
                    billing_amount:      0,
                    last_edited_date:    '2015/09/18',
                    last_editor_code:    '1853',
                    last_editor_account: 'm-perry',
                },
                {
                    code: '   1333',
                    name:     'ナニ',
                    maker:    'ちびまるこちゃん',
                    min_price:    41.35,
                    cur_price:    41.41,
                    max_price:    41.92,
                    quantity: 9,
                    state:    'CANCELED',
                    billing_amount:      0,
                    last_edited_date:    '2015/09/18',
                    last_editor_code:    '1853',
                    last_editor_account: 'm-perry',
                },
                {
                    code: '   1549',
                    name:     'ドレ?',
                    maker:    'サザエさん',
                    min_price:    33.00,
                    cur_price:    33.50,
                    max_price:    33.99,
                    quantity: 1000,
                    state:    'DELIVERED',
                    billing_amount:      33800,
                    last_edited_date:    '2015/09/18',
                    last_editor_code:    '1853',
                    last_editor_account: 'm-perry',
                }
            ],
            last_modified_date: '2015/10/10',
            last_modifier_code: '1603',
            last_modifier_account: 'k-katsu'
        },
        {
            order_code:      '4351',
            order_type:      'MEDS_ORDER',
            order_state:     'NULLIFIED',
            order_remark:    '怒り? 哀しみ? 喜び? 喜怒哀楽?',
            drafting_date:   '2015/08/01',
            drafter_code:    '1853',
            drafter_account: 'm-perry',
            department_code: '0003',
            department_name: '小児科',
            trader_code:     '0003',
            trader_name:     'エセショップ',
            products: [
                {
                    code:     '0001',
                    name:     '危険薬',
                    maker:    '酩酊ラリ子',
                    min_price:    42.19,
                    cur_price:    42.19,
                    max_price:    42.19,
                    quantity: 666,
                    state:    'CANCELED',
                    billing_amount:      0,
                    last_edited_date:    '2015/09/18',
                    last_editor_code:    '1853',
                    last_editor_account: 'm-perry',
                },
            ],
            last_modified_date:    '2015/10/10',
            last_modifier_code:    '1603',
            last_modifier_account: 'k-katsu'
        }],
    });
};
